spring:
  profiles:
    active: dev
#server:
#  servlet:
#    context-path: /api/
jwt:
  expiresSecond: 5184000000
  base64Secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxMjMiLCJleHAiOjE1NDA0MzYxMzYsIm5iZiI6MTU0MDI2MzMzNn0.Q7FKiYp2W-V8cBIP9zEkxO7cpH9MER-aM6q_0lOZeHA=
  redisPrefix: update_password_time:%s
qiniu:
  accessKey: _I-tvI9XSNEzwjzeEWz3KxfBQwL9mk3GOcDbNKST
  secretKey: DMEfYejDMunmcgz07VfUraR9OhEvRX_ekY58H-2w
  bucket: secdra
