server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secdra?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
base:
  verificationCodePrefix: verification_code:%s
  jwtExpiresSecond: 5184000000
  jwtBase64Secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxMjMiLCJleHAiOjE1NDA0MzYxMzYsIm5iZiI6MTU0MDI2MzMzNn0.Q7FKiYp2W-V8cBIP9zEkxO7cpH9MER-aM6q_0lOZeHA=
  updatePasswordTimePrefix: base:update_password_time:%s
  qiniuAccessKey: 0G397Ly7Z6pqnm2MPUhHIbMFzvBX19yyhu-RdiqI
  qiniuSecretKey: _xLtVKJ4VNUrwSsEGkJBHtV2s6mZ2QG2yDXaCvTk
  qiniuTempBucket: temporary
  qiniuHeadBucket: head
  qiniuBackBucket: background
  qiniuBucket: secdra
  qiniuTempBucketUrl: http://secdratemp.secdra.com
  qiniuHeadBucketUrl: http://secdrahead.secdra.com
  qiniuBackBucketUrl: http://secdraback.secdra.com
  qiniuBucketUrl: http://secdraimg.secdra.com


