server:
  port: 8080
spring:
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secdra?useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
base:
  verificationCodePrefix: verification_code:%s
  jwtExpiresSecond: 5184000000
  jwtSecretString: www.secdra.com
  updatePasswordTimePrefix: base:update_password_time:%s
  notUUID: 00000000000000000000000000000000
  qiniuAccessKey: XXX
  qiniuSecretKey: XXX
  qiniuTempBucket: temporary
  qiniuHeadBucket: head
  qiniuBackBucket: background
  qiniuBucket: secdra
  qiniuTempBucketUrl: http://secdratemp.secdra.com
  qiniuHeadBucketUrl: http://secdrahead.secdra.com
  qiniuBackBucketUrl: http://secdraback.secdra.com
  qiniuBucketUrl: http://secdraimg.secdra.com