spring:
  profiles:
    active: dev
#server:
#  servlet:
#    context-path: /api/
base:
  verificationCodePrefix: verification_code:%s
  jwtExpiresSecond: 5184000000
  jwtBase64Secret: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VySWQiOiIxMjMiLCJleHAiOjE1NDA0MzYxMzYsIm5iZiI6MTU0MDI2MzMzNn0.Q7FKiYp2W-V8cBIP9zEkxO7cpH9MER-aM6q_0lOZeHA=
  updatePasswordTimePrefix: base:update_password_time:%s
  qiniuAccessKey: _I-tvI9XSNEzwjzeEWz3KxfBQwL9mk3GOcDbNKST
  qiniuSecretKey: DMEfYejDMunmcgz07VfUraR9OhEvRX_ekY58H-2w
  qiniuTempBucket: temporary
  qiniuHeadBucket: head
  qiniuBackBucket: background
  qiniuBucket: secdra
  qiniuTempBucketUrl: http://phnqxaco3.bkt.clouddn.com
  qiniuHeadBucketUrl: http://phnqizf7z.bkt.clouddn.com
  qiniuBackBucketUrl: http://phnqlj10o.bkt.clouddn.com
  qiniuBucketUrl: http://ph9jy186h.bkt.clouddn.com


