server:
  port: 8080

spring:
  devtools:
    restart:
      enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/secdra
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
#  mvc:
#    static-path-pattern: /static/**



